COUNTIES = {
    "NJ": {
        "Sussex",
        "Warren",
        "Hunterdon",
        "Morris",
        "Passaic",
        "Bergen",
        "Essex",
        "Hudson",
        "Union",
        "Somerset",
        "Middlesex",
        "Monmouth",
        "Ocean",
        "Mercer",
        "Burlington",
        "Camden",
        "Gloucester",
        "Salem",
        "Cumberland",
        "Cape May",
        "Atlantic",
    },
    "PA": {
        "Adams",
        "Allegheny",
        "Armstrong",
        "Beaver",
        "Bedford",
        "Berks",
        "Blair",
        "Bradford",
        "Bucks",
        "Butler",
        "Cambria",
        "Cameron",
        "Carbon",
        "Centre",
        "Chester",
        "Clarion",
        "Clearfield",
        "Clinton",
        "Columbia",
        "Crawford",
        "Cumberland",
        "Dauphin",
        "Delaware",
        "Elk",
        "Erie",
        "Fayette",
        "Forest",
        "Franklin",
        "Fulton",
        "Greene",
        "Huntingdon",
        "Indiana",
        "Jefferson",
        "Juniata",
        "Lackawanna",
        "Lancaster",
        "Lawrence",
        "Lebanon",
        "Lehigh",
        "Luzerne",
        "Lycoming",
        "McKean",
        "Mercer",
        "Mifflin",
        "Monroe",
        "Montgomery",
        "Montour",
        "Northampton",
        "Northumberland",
        "Perry",
        "Philadelphia",
        "Pike",
        "Potter",
        "Schuylkill",
        "Snyder",
        "Somerset",
        "Sullivan",
        "Susquehanna",
        "Tioga",
        "Union",
        "Venango",
        "Warren",
        "Washington",
        "Wayne",
        "Westmoreland",
        "Wyoming",
        "York",
    },
    "MI": {
        "Alcona",
        "Alger",
        "Allegan",
        "Alpena",
        "Antrim",
        "Arenac",
        "Baraga",
        "Barry",
        "Bay",
        "Benzie",
        "Berrien",
        "Branch",
        "Calhoun",
        "Cass",
        "Charlevoix",
        "Cheboygan",
        "Chippewa",
        "Clare",
        "Clinton",
        "Crawford",
        "Delta",
        "Dickinson",
        "Eaton",
        "Emmet",
        "Genesee",
        "Gladwin",
        "Gogebic",
        "Grand Traverse",
        "Gratiot",
        "Hillsdale",
        "Houghton",
        "Huron",
        "Ingham",
        "Ionia",
        "Iosco",
        "Iron",
        "Isabella",
        "Jackson",
        "Kalamazoo",
        "Kalkaska",
        "Kent",
        "Keweenaw",
        "Lake",
        "Lapeer",
        "Leelanau",
        "Lenawee",
        "Livingston",
        "Luce",
        "Mackinac",
        "Macomb",
        "Manistee",
        "Marquette",
        "Mason",
        "Mecosta",
        "Menominee",
        "Midland",
        "Missaukee",
        "Monroe",
        "Montcalm",
        "Montmorency",
        "Muskegon",
        "Newaygo",
        "Oakland",
        "Oceana",
        "Ogemaw",
        "Ontonagon",
        "Osceola",
        "Oscoda",
        "Otsego",
        "Ottawa",
        "Presque Isle",
        "Roscommon",
        "Saginaw",
        "St. Clair",
        "St. Joseph",
        "Sanilac",
        "Schoolcraft",
        "Shiawassee",
        "Tuscola",
        "Van Buren",
        "Washtenaw",
        "Wayne",
        "Wexford",
    },
    "WI": {
        "Adams",
        "Ashland",
        "Barron",
        "Bayfield",
        "Brown",
        "Buffalo",
        "Burnett",
        "Calumet",
        "Chippewa",
        "Clark",
        "Columbia",
        "Crawford",
        "Dane",
        "Dodge",
        "Door",
        "Douglas",
        "Dunn",
        "Eau Claire",
        "Florence",
        "Fond du Lac",
        "Forest",
        "Grant",
        "Green",
        "Green Lake",
        "Iowa",
        "Iron",
        "Jackson",
        "Jefferson",
        "Juneau",
        "Kenosha",
        "Kewaunee",
        "La Crosse",
        "Lafayette",
        "Langlade",
        "Lincoln",
        "Manitowoc",
        "Marathon",
        "Marinette",
        "Marquette",
        "Menominee",
        "Milwaukee",
        "Monroe",
        "Oconto",
        "Oneida",
        "Outagamie",
        "Ozaukee",
        "Pepin",
        "Pierce",
        "Polk",
        "Portage",
        "Price",
        "Racine",
        "Richland",
        "Rock",
        "Rusk",
        "St. Croix",
        "Sauk",
        "Sawyer",
        "Shawano",
        "Sheboygan",
        "Taylor",
        "Trempealeau",
        "Vernon",
        "Vilas",
        "Walworth",
        "Washburn",
        "Washington",
        "Waukesha",
        "Waupaca",
        "Waushara",
        "Winnebago",
        "Wood",
    },
    "NC": {
        "Alamance",
        "Alexander",
        "Alleghany",
        "Anson",
        "Ashe",
        "Avery",
        "Beaufort",
        "Bertie",
        "Bladen",
        "Brunswick",
        "Buncombe",
        "Burke",
        "Cabarrus",
        "Caldwell",
        "Camden",
        "Carteret",
        "Caswell",
        "Catawba",
        "Chatham",
        "Cherokee",
        "Chowan",
        "Clay",
        "Cleveland",
        "Columbus",
        "Craven",
        "Cumberland",
        "Currituck",
        "Dare",
        "Davidson",
        "Davie",
        "Duplin",
        "Durham",
        "Edgecombe",
        "Forsyth",
        "Franklin",
        "Gaston",
        "Gates",
        "Granville",
        "Greene",
        "Guilford",
        "Halifax",
        "Harnett",
        "Haywood",
        "Henderson",
        "Hertford",
        "Hoke",
        "Hyde",
        "Iredell",
        "Jackson",
        "Johnston",
        "Jones",
        "Lee",
        "Lenoir",
        "Lincoln",
        "McDowell",
        "Macon",
        "Madison",
        "Martin",
        "Mecklenburg",
        "Mitchell",
        "Montgomery",
        "Moore",
        "Nash",
        "New Hanover",
        "Northampton",
        "Onslow",
        "Orange",
        "Pamlico",
        "Pasquotank",
        "Pender",
        "Perquimans",
        "Person",
        "Pitt",
        "Polk",
        "Randolph",
        "Richmond",
        "Robeson",
        "Rockingham",
        "Rowan",
        "Rutherford",
        "Sampson",
        "Scotland",
        "Stanly",
        "Stokes",
        "Surry",
        "Swain",
        "Transylvania",
        "Tyrrell",
        "Union",
        "Vance",
        "Wake",
        "Warren",
        "Washington",
        "Wayne",
        "Wilkes",
        "Wilson",
        "Yadkin",
    },
    "GA": {
        "Appling",
        "Atkinson",
        "Bacon",
        "Baker",
        "Baldwin",
        "Banks",
        "Barrow",
        "Bartow",
        "Ben Hill",
        "Berrien",
        "Bibb",
        "Bleckley",
        "Brantley",
        "Brooks",
        "Bryan",
        "Bulloch",
        "Burke",
        "Butts",
        "Calhoun",
        "Camden",
        "Candler",
        "Carroll",
        "Catoosa",
        "Charlton",
        "Chatham",
        "Chattahoochee",
        "Chattooga",
        "Cherokee",
        "Clarke",
        "Clayton",
        "Clinch",
        "Cobb",
        "Coffee",
        "Colquitt",
        "Columbia",
        "Cook",
        "Coweta",
        "Crawford",
        "Crisp",
        "Dade",
        "Dawson",
        "Decatur",
        "DeKalb",
        "Dodge",
        "Dooly",
        "Dougherty",
        "Douglas",
        "Early",
        "Echols",
        "Effingham",
        "Elbert",
        "Emanuel",
        "Evans",
        "Fannin",
        "Fayette",
        "Floyd",
        "Forsyth",
        "Franklin",
        "Fulton",
        "Gilmer",
        "Glascock",
        "Glynn",
        "Gordon",
        "Grady",
        "Greene",
        "Gwinnett",
        "Habersham",
        "Hall",
        "Hancock",
        "Haralson",
        "Harris",
        "Hart",
        "Heard",
        "Henry",
        "Houston",
        "Irwin",
        "Jackson",
        "Jasper",
        "Jeff Davis",
        "Jefferson",
        "Jenkins",
        "Johnson",
        "Jones",
        "Lamar",
        "Lanier",
        "Laurens",
        "Lee",
        "Liberty",
        "Lincoln",
        "Long",
        "Lowndes",
        "Lumpkin",
        "McDuffie",
        "McIntosh",
        "Macon",
        "Madison",
        "Marion",
        "Meriwether",
        "Millage",
        "Mitchell",
        "Monroe",
        "Montgomery",
        "Morgan",
        "Murray",
        "Muscogee",
        "Newton",
        "Oconee",
        "Oglethorpe",
        "Paulding",
        "Peach",
        "Pickens",
        "Pierce",
        "Pike",
        "Polk",
        "Pulaski",
        "Putnam",
        "Quitman",
        "Rabun",
        "Randolph",
        "Richmond",
        "Rockdale",
        "Schley",
        "Screven",
        "Seminole",
        "Spalding",
        "Stephens",
        "Stewart",
        "Sumter",
        "Talbot",
        "Taliaferro",
        "Tattnall",
        "Taylor",
        "Telfair",
        "Terrell",
        "Thomas",
        "Tift",
        "Toombs",
        "Towns",
        "Treutlen",
        "Troup",
        "Turner",
        "Twiggs",
        "Union",
        "Upson",
        "Walker",
        "Walton",
        "Ware",
        "Warren",
        "Washington",
        "Wayne",
        "Webster",
        "Wheeler",
        "White",
        "Whitfield",
        "Wilcox",
        "Wilkes",
        "Wilkinson",
        "Worth",
    },
    "FL": {
        "Alachua",
        "Baker",
        "Bay",
        "Bradford",
        "Brevard",
        "Broward",
        "Calhoun",
        "Charlotte",
        "Citrus",
        "Clay",
        "Collier",
        "Columbia",
        "DeSoto",
        "Dixie",
        "Duval",
        "Escambia",
        "Flagler",
        "Franklin",
        "Gadsden",
        "Gilchrist",
        "Glades",
        "Gulf",
        "Hamilton",
        "Hardee",
        "Hendry",
        "Hernando",
        "Highlands",
        "Hillsborough",
        "Holmes",
        "Indian River",
        "Jackson",
        "Jefferson",
        "Lafayette",
        "Lake",
        "Lee",
        "Leon",
        "Levy",
        "Liberty",
        "Madison",
        "Manatee",
        "Marion",
        "Martin",
        "Miami-Dade",
        "Monroe",
        "Nassau",
        "Okaloosa",
        "Okeechobee",
        "Orange",
        "Osceola",
        "Palm Beach",
        "Pasco",
        "Pinellas",
        "Polk",
        "Putnam",
        "St. Johns",
        "St. Lucie",
        "Santa Rosa",
        "Sarasota",
        "Seminole",
        "Sumter",
        "Suwannee",
        "Taylor",
        "Union",
        "Volusia",
        "Wakulla",
        "Walton",
        "Washington",
    },
    "VA": {
        "Accomack",
        "Albemarle",
        "Alleghany",
        "Amelia",
        "Amherst",
        "Appomattox",
        "Arlington",
        "Augusta",
        "Bath",
        "Bedford",
        "Bland",
        "Botetourt",
        "Brunswick",
        "Buchanan",
        "Buckingham",
        "Campbell",
        "Caroline",
        "Carroll",
        "Charles City",
        "Charlotte",
        "Chesterfield",
        "Clarke",
        "Craig",
        "Culpeper",
        "Cumberland",
        "Dickenson",
        "Dinwiddie",
        "Essex",
        "Fairfax",
        "Fauquier",
        "Floyd",
        "Fluvanna",
        "Franklin",
        "Frederick",
        "Giles",
        "Gloucester",
        "Goochland",
        "Grayson",
        "Greene",
        "Greensville",
        "Halifax",
        "Hanover",
        "Henrico",
        "Henry",
        "Highland",
        "Isle of Wight",
        "James City",
        "King and Queen",
        "King George",
        "King William",
        "Lancaster",
        "Lee",
        "Loudoun",
        "Louisa",
        "Lunenburg",
        "Madison",
        "Mathews",
        "Mecklenburg",
        "Middlesex",
        "Montgomery",
        "Nelson",
        "New Kent",
        "Northampton",
        "Northumberland",
        "Nottoway",
        "Orange",
        "Page",
        "Patrick",
        "Pittsylvania",
        "Powhatan",
        "Prince Edward",
        "Prince George",
        "Prince William",
        "Pulaski",
        "Rappahannock",
        "Richmond",
        "Roanoke",
        "Rockbridge",
        "Rockingham",
        "Russell",
        "Scott",
        "Shenandoah",
        "Smyth",
        "Southampton",
        "Spotsylvania",
        "Stafford",
        "Surry",
        "Sussex",
        "Tazewell",
        "Warren",
        "Washington",
        "Westmoreland",
        "Wise",
        "Wythe",
        "York",
        "Alexandria city",
        "Bristol city",
        "Buena Vista city",
        "Charlottesville city",
        "Chesapeake city",
        "Colonial Heights city",
        "Covington city",
        "Danville city",
        "Emporia city",
        "Fairfax city",
        "Falls Church city",
        "Franklin city",
        "Fredericksburg city",
        "Galax city",
        "Hampton city",
        "Harrisonburg city",
        "Hopewell city",
        "Lexington city",
        "Lynchburg city",
        "Manassas city",
        "Manassas Park city",
        "Martinsville city",
        "Newport News city",
        "Norfolk city",
        "Norton city",
        "Petersburg city",
        "Poquoson city",
        "Portsmouth city",
        "Radford city",
        "Richmond city",
        "Roanoke city",
        "Salem city",
        "Staunton city",
        "Suffolk city",
        "Virginia Beach city",
        "Waynesboro city",
        "Williamsburg city",
        "Winchester city",
    },
    "NH": {
        "Belknap",
        "Carroll",
        "Cheshire",
        "Coos",
        "Grafton",
        "Hillsborough",
        "Merrimack",
        "Rockingham",
        "Strafford",
        "Sullivan",
    },
    "AZ": {
        "Apache",
        "Cochise",
        "Coconino",
        "Gila",
        "Graham",
        "Greenlee",
        "La Paz",
        "Maricopa",
        "Mohave",
        "Navajo",
        "Pima",
        "Pinal",
        "Santa Cruz",
        "Yavapai",
        "Yuma",
    },
    "NV": {
        "Churchill",
        "Clark",
        "Douglas",
        "Elko",
        "Esmeralda",
        "Eureka",
        "Humboldt",
        "Lander",
        "Lincoln",
        "Lyon",
        "Mineral",
        "Nye",
        "Pershing",
        "Storey",
        "Washoe",
        "White Pine",
        "Carson City",
    },
}
